[package]
name = "kwality-runtime-validator"
version = "1.0.0"
edition = "2021"
authors = ["Kwality Team"]
description = "Runtime validation engine for AI-generated code"
license = "MIT"
repository = "https://github.com/KooshaPari/kwality"

[dependencies]
tokio = { version = "1.34", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.5", features = ["v4", "serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0"
thiserror = "1.0"
clap = { version = "4.4", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
bollard = "0.15"  # Docker API client
tempfile = "3.8"
criterion = { version = "0.5", features = ["html_reports"] }
sysinfo = "0.29"
regex = "1.10"
walkdir = "2.4"
sha2 = "0.10"
async-trait = "0.1"
futures-util = "0.3"  # For streaming operations with Docker
rand = "0.8"  # For random number generation in fuzzing
chrono = { version = "0.4", features = ["serde"] }  # For date/time handling
levenshtein = "1.0"  # For string distance calculations in fuzzing
num_cpus = "1.0"  # For CPU count detection

[dev-dependencies]
tokio-test = "0.4"
proptest = "1.4"
mockall = "0.12"

[[bin]]
name = "kwality-runtime"
path = "src/main.rs"

[lib]
name = "kwality_runtime_validator"
path = "src/lib.rs"